// Single source of truth for which demo pages each harness covers. Tag a page
// with the harnesses that should run it:
//   shoot  — exhaustive screenshot sweep (every page)
//   visual — pixel-diff regression gate (representative subset)
//   a11y   — axe gate (representative subset)
// Adding a demo? Add one row here with the right tags — no more editing three
// divergent lists (which is how app/survey ended up in two of them, not all).
export const PAGES = [
  { name: 'index', tags: ['shoot'] },
  { name: 'strata', tags: ['visual', 'a11y'] },
  { name: 'foundations/typography', tags: ['shoot'] },
  { name: 'foundations/layout', tags: ['shoot'] },
  { name: 'foundations/forms', tags: ['shoot', 'visual', 'a11y'] },
  { name: 'app/components', tags: ['shoot', 'visual', 'a11y'] },
  { name: 'app/admin', tags: ['shoot', 'visual'] },
  { name: 'app/errors', tags: ['shoot'] },
  { name: 'app/survey', tags: ['visual', 'a11y'] },
  { name: 'site/landing', tags: ['shoot', 'visual', 'a11y'] },
  { name: 'site/minimal', tags: ['shoot'] },
  { name: 'site/product', tags: ['shoot'] },
  { name: 'site/startup', tags: ['shoot'] },
  { name: 'site/app', tags: ['shoot'] },
  { name: 'site/event', tags: ['shoot'] },
  { name: 'site/agency', tags: ['shoot'] },
  { name: 'site/newsletter', tags: ['shoot'] },
  { name: 'site/coming-soon', tags: ['shoot'] },
  { name: 'site/waitlist', tags: ['shoot'] },
  { name: 'content/blog', tags: ['shoot', 'visual'] },
  { name: 'content/blog-medium', tags: ['shoot'] },
  { name: 'content/article', tags: ['shoot', 'visual', 'a11y'] },
  { name: 'content/article-plain', tags: ['shoot'] },
  { name: 'content/article-media', tags: ['shoot'] },
  { name: 'auth/sign-in', tags: ['shoot', 'visual', 'a11y'] },
  { name: 'auth/sign-in-centered', tags: ['shoot'] },
  { name: 'auth/sign-up', tags: ['shoot'] },
  { name: 'auth/reset', tags: ['shoot'] },
  { name: 'auth/check-email', tags: ['shoot'] },
  { name: 'auth/new-password', tags: ['shoot'] },
  { name: 'auth/verify', tags: ['shoot'] },
  { name: 'auth/two-factor', tags: ['shoot'] },
  { name: 'auth/passwordless', tags: ['shoot'] },
  { name: 'auth/app-password', tags: ['shoot'] },
  { name: 'email/index', tags: ['shoot'] },
  { name: 'email/transactional', tags: ['shoot'] },
  { name: 'email/newsletter', tags: ['shoot'] },
  { name: 'media/index', tags: ['shoot', 'visual'] },
  { name: 'media/video', tags: ['shoot'] },
  { name: 'media/audio', tags: ['shoot'] },
  { name: 'media/social', tags: ['shoot'] },
  { name: 'commerce/products', tags: ['shoot'] },
  { name: 'commerce/product', tags: ['shoot', 'visual'] },
  { name: 'commerce/cart', tags: ['shoot'] },
  { name: 'commerce/checkout', tags: ['shoot'] },
  { name: 'commerce/order', tags: ['shoot'] },
  { name: 'billing/plans', tags: ['shoot'] },
  { name: 'billing/methods', tags: ['shoot'] },
  { name: 'billing/invoices', tags: ['shoot'] },
  { name: 'billing/overview', tags: ['shoot', 'a11y'] },
  { name: 'docs/guide', tags: ['shoot', 'a11y'] },
  { name: 'docs/api', tags: ['shoot'] },
  { name: 'docs/help', tags: ['shoot'] },
  { name: 'docs/article', tags: ['shoot'] },
  { name: 'support/contact', tags: ['shoot'] },
  { name: 'support/tickets', tags: ['shoot'] },
  { name: 'support/ticket', tags: ['shoot', 'a11y'] },
];

export const urlFor = (name) => `/demo/${name}.html`;
export const pagesFor = (tag) => PAGES.filter((p) => p.tags.includes(tag)).map((p) => p.name);
