// Generate the Tokens reference page from tokens/tokens.json so the docs never
// drift from the source of truth. Emits src/content/docs/foundations/tokens.md.
// Re-run via `npm run gen` (also runs automatically on predev/prebuild).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, '..', '..');
const OUT = path.resolve(__dirname, '..', 'src', 'content', 'docs', 'foundations', 'tokens.md');

const tokens = JSON.parse(fs.readFileSync(path.join(REPO, 'tokens', 'tokens.json'), 'utf8'));

const swatch = (v) =>
  `<span style="display:inline-block;width:16px;height:16px;border-radius:4px;border:1px solid var(--sl-color-gray-5);background:${v};vertical-align:middle"></span>`;

function colorTable(group) {
  const rows = Object.entries(group)
    .map(([k, t]) => `| \`--${k}\` | ${swatch(t.value)} | \`${t.value}\` |`)
    .join('\n');
  return `| Token | | Value |\n| --- | --- | --- |\n${rows}`;
}

function scaleTable(group, label = 'Token') {
  const rows = Object.entries(group)
    .map(([k, t]) => `| \`${k}\` | \`${t.value}\` |`)
    .join('\n');
  return `| ${label} | Value |\n| --- | --- |\n${rows}`;
}

const md = `---
title: Tokens
description: Every design token in Qazana Strata, generated from tokens.json — the single source of truth.
sidebar:
  order: 1
---

<!-- AUTO-GENERATED by docs-site/scripts/gen-tokens.mjs — edit tokens.json, not this file. -->

Tokens are the contract. Components never hardcode a colour, space, radius, shadow,
font or duration — they reference one of these. A single per-product override
re-skins everything. Each colour also ships as an \`-rgb\` channel triple so alpha
tints stay themeable: \`rgb(var(--primary-rgb) / .12)\`.

## Colour — Dark Knight (canonical)

${colorTable(tokens.color)}

## Colour — Désert Dunes (light)

${colorTable(tokens['color-light'])}

## Spacing

${scaleTable(tokens.space, 'Step')}

## Radius

${scaleTable(tokens.radius)}

## Shadow

${scaleTable(tokens.shadow)}

## Type — families

${scaleTable(tokens.font)}

## Type — scale (font-size)

${scaleTable(tokens.fontSize, 'Step')}

## Type — line-height

${scaleTable(tokens.lineHeight)}

## Type — tracking (letter-spacing)

${scaleTable(tokens.letterSpacing)}

## Type — weight

${scaleTable(tokens.fontWeight)}

## Type — measure

${scaleTable(tokens.measure)}

## Motion

${scaleTable(tokens.motion)}

---

> This page is generated from \`tokens/tokens.json\`. To change a value, edit the
> token there (and keep \`tokens/qazana.tokens.css\` in sync), then re-run \`npm run gen\`.
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, md);
console.log(`[gen] wrote ${path.relative(REPO, OUT)}`);
